name: build

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependency
        run: yarn install

      - name: Run Lint
        run: yarn run lint


  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ ^20 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependency
        run: yarn install

      - name: Run Unit test
        run: yarn run test
